name: Java CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Get build artifact ready
        run: mkdir staging && cp target/*.jar staging
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
      - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.4
     
